### ISSUE TITLE
5 point scale cleanup

### ISSUE THREAD

**Issue by hadley** [COSTDataExpo2013/MaurerOsthusLoy#2]
I have two concerns about the factor level cleanup code:
1. Code like this is extremely fragile because it relies on the factor levels always being in the same order (which may not be true when you run on different computers)
   
   ``` R
   levels(dat$comSat)[7] <- "5"
   levels(dat$comSat)[8] <- "1"
   ```
   
   It's also copy-and-pasted in many places, which makes it easy for 
   a small error to creep in. Could you please make into a more robust
   function?
2.  Some of the factor cleanup will create duplicated levels:
   
   ``` R
   levels(dat$closeFriends)[7] <- "Most"
   ```
   
   This results in `closeFriends` having two different levels with the 
   same value. I don't know what impact this has, but it seems risky.

**Comment by aloy** [comment]
I addressed both of your concerns by using plyr::revalue
